onboarding = false

[theme]
name = "gruvbox"

[keys]
open_worktree = "prefix+shift+o"
remove_worktree = "prefix+shift+d"

[ui]
prompt_new_tab_name = true
pane_scrollbars = false
tab_bar_position = "bottom"

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"
