onboarding = false

[theme]
name = "gruvbox"

[keys]
open_worktree = "prefix+shift+o"
remove_worktree = "prefix+alt+d"

[ui]
prompt_new_tab_name = true

[ui.toast]
delivery = "herdr"

[ui.toast.herdr]
position = "top-right"
