#!/usr/bin/env bash

info_message() {
    echo "$(tput setaf 2)[INFO] $(tput sgr0)$1"
}

if ! command -v eza &> /dev/null; then
    info_message "Installing eza..."
    wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
    echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
    sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
    sudo apt-get update
    sudo apt-get install -y eza
else
    info_message "eza is already installed."
fi