#!/usr/bin/env bash
set -eo pipefail

ARCHIVE_NAME="FirefoxDeveloperEdition.dmg"
DOWNLOAD_URL="https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=osx&lang=en-US"
INSTALL_DIR="/Applications"

TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
curl -L "$DOWNLOAD_URL" -o "$ARCHIVE_NAME"

hdiutil mount "$ARCHIVE_NAME" > /dev/null

cp -R "/Volumes/Firefox Developer Edition/Firefox Developer Edition.app" "$INSTALL_DIR/"

hdiutil unmount "/Volumes/Firefox Developer Edition/" > /dev/null

# now for extensions, install the following
# bitwarden - https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/
# reader readwise - https://addons.mozilla.org/en-US/firefox/addon/readwise-highlighter/
# ublock origin - https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
# privacy badger - https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/
# tab reloader - https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/
# and you are good to go.
