#!/usr/bin/env bash
set -eo pipefail

VERSION='1.1.3'
ARCHIVE_NAME="Ghostty.dmg"
DOWNLOAD_URL="https://release.files.ghostty.org/$VERSION/$ARCHIVE_NAME"
INSTALL_DIR="/Applications"

TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
curl -L "$DOWNLOAD_URL" -o "$ARCHIVE_NAME"

hdiutil mount "$ARCHIVE_NAME" > /dev/null

cp -R "/Volumes/Ghostty/Ghostty.app" "$INSTALL_DIR/"

hdiutil unmount "/Volumes/Ghostty/" > /dev/null
