#!/usr/bin/env bash
set -eo pipefail

VERSION='v0.11.0'
ARCHIVE_NAME="nvim-macos-arm64.tar.gz"
DOWNLOAD_URL="https://github.com/neovim/neovim/releases/download/$VERSION/$ARCHIVE_NAME"
INSTALL_DIR="$HOME/.local/bin"

TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
curl -LO $DOWNLOAD_URL
xattr -c ./$ARCHIVE_NAME
tar xzf $ARCHIVE_NAME
cp -f nvim-macos-arm64/bin/nvim "$INSTALL_DIR/"
chmod +x "$INSTALL_DIR/nvim"
