#!/usr/bin/env bash
set -eo pipefail

VERSION='v0.179.5'
ARCHIVE_NAME="Zed-aarch64.dmg"
DOWNLOAD_URL="https://github.com/zed-industries/zed/releases/download/$VERSION/$ARCHIVE_NAME"
INSTALL_DIR="/Applications"

TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
curl -L "$DOWNLOAD_URL" -o "$ARCHIVE_NAME"

hdiutil mount "$ARCHIVE_NAME" > /dev/null

cp -R "/Volumes/Zed/Zed.app" "$INSTALL_DIR/"

hdiutil unmount "/Volumes/Zed/" > /dev/null
